"""Tests for the PMI event implementation.

Generated by ``EventScaffolder`` and customized for PMI semantics.
"""

from pathlib import Path
import pandas as pd
import pytest

from knowledge.events.pmi import PMIEvent
from knowledge.features.extractors.pmi import (
    PMIFeatureExtractor,
)
from knowledge.builders.lesson_builder import (
    LessonBuilder,
    LessonBuilderConfig,
    LegacyLessonBuilder,
)
from knowledge.lesson_summary import LessonSummaryAggregator, LessonSummaryConfig
from knowledge.events.registry import EventRegistry


@pytest.fixture(autouse=True)
def _ensure_pmi_registered() -> None:
    if not EventRegistry.is_registered("PMI"):
        EventRegistry.register(PMIEvent)


class TestPMIEventFeatureExtractor:
    """Feature extraction tests."""

    def test_defines_features(self) -> None:
        ext = PMIFeatureExtractor()
        assert "previous_value" in ext.feature_definitions
        assert "pmi_change" in ext.feature_definitions
        assert "pmi_trend" in ext.feature_definitions

    def test_classifies_condition(self) -> None:
        assert PMIFeatureExtractor._classify_condition(51) == "pmi_expansion"
        assert PMIFeatureExtractor._classify_condition(49) == "pmi_contraction"
        assert PMIFeatureExtractor._classify_condition(50) == "pmi_neutral"

    def test_extract_adds_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,52\n2024-02-10,55\n")
        ext = PMIFeatureExtractor()
        raw = pd.read_csv(csv)
        result = ext.extract(raw)
        assert "pmi_change" in result.data.columns
        assert "pmi_trend" in result.data.columns
        # After dropna, first surviving row has Value=55 → change=3 → expansion
        assert result.data["pmi_trend"].iloc[0] == "pmi_expansion"


class TestPMIEventTypeStrings:
    """Event metadata string constants."""

    def test_event_type(self) -> None:
        assert PMIEvent.event_type == "PMI"

    def test_lesson_version(self) -> None:
        assert PMIEvent.lesson_version == "pmi_gold_v1"

    def test_condition_columns(self) -> None:
        assert PMIEvent.condition_columns == ['pmi_trend']

    def test_knowledge_version(self) -> None:
        assert PMIEvent.knowledge_version == "pmi_gold_summary_v1"


class TestPMIEventMetadata:
    """StandardEventMetadata tests."""

    def test_metadata_returns_expected_values(self) -> None:
        ev = PMIEvent()
        m = ev.metadata
        assert m is not None
        assert m.country == "US"
        assert m.currency == "USD"
        assert m.unit == "index"
        assert m.importance == 3


class TestPMIEventLoadRaw:
    """Raw data loading tests."""

    def test_returns_date_value_only(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,52\n")
        ev = PMIEvent()
        df = ev.load_raw(csv)
        assert list(df.columns) == ["Date", "Value"]

    def test_sorts_and_deduplicates(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text(
            "Date,Value\n2024-01-10,52\n2024-01-10,53\n"
            "2024-01-05,50\n"
        )
        ev = PMIEvent()
        df = ev.load_raw(csv)
        assert len(df) == 2
        assert df["Date"].iloc[0].date().isoformat() == "2024-01-05"

    def test_raises_on_missing_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "bad.csv"
        csv.write_text("Col1,Col2\n1,2\n")
        ev = PMIEvent()
        with pytest.raises(ValueError, match="missing required columns"):
            ev.load_raw(csv)


class TestPMIEventLoadAndExtract:
    """Full load + extract pipeline tests."""

    def test_includes_all_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,52\n2024-02-10,55\n")
        ev = PMIEvent()
        df = ev.load_and_extract(csv)
        assert "Date" in df.columns
        assert "pmi_change" in df.columns
        assert "pmi_trend" in df.columns

    def test_empty_on_single_row(self, tmp_path: Path) -> None:
        csv = tmp_path / "single.csv"
        csv.write_text("Date,Value\n2024-01-10,52\n")
        ev = PMIEvent()
        df = ev.load_and_extract(csv)
        assert len(df) == 0


class TestPMIEventLesson:
    """Lesson field and text tests."""

    def test_build_lesson_fields(self) -> None:
        ev = PMIEvent()
        row = pd.Series({
            "Date": pd.Timestamp("2024-01-10"),
            "Value": 55.0,
            "previous_value": 52.0,
            "pmi_change": 3.0,
            "pmi_trend": "pmi_expansion",
        })
        fields = ev.build_lesson_fields(row, "2024-01-10")
        assert "pmi_value" in fields
        assert "pmi_change" in fields
        assert "pmi_trend" in fields

    def test_lesson_text(self) -> None:
        ev = PMIEvent()
        lesson = {
            "event_date": "2024-01-10",
            "primary_horizon_days": 5,
            "gold_direction_5d": "UP",
            "gold_return_5d_pct": 1.5,
            "pmi_value": 55.0,
            "pmi_trend": "pmi_expansion",
        }
        text = ev.lesson_text(lesson)
        assert "PMI" in text
        assert "55.0" in text
        assert "pmi_expansion" in text


class TestPMIEventRegistry:
    """Registry integration tests."""

    def test_is_registered_after_import(self) -> None:
        assert EventRegistry.is_registered("PMI")

    def test_can_be_instantiated_from_registry(self) -> None:
        cls = EventRegistry.get("PMI")
        assert cls is not None
        instance = cls()
        assert instance.event_type == "PMI"


class TestPMIEventPipelineEndToEnd:
    """End-to-end: LessonBuilder -> LessonSummaryAggregator."""

    def test_knowledge_from_pmi_lessons(
        self, tmp_path: Path
    ) -> None:
        ev = PMIEvent()
        data_csv = tmp_path / "pmi.csv"
        data_csv.write_text(
            "Date,Value\n2024-01-10,52\n2024-02-10,55\n"
            "2024-03-10,48\n"
        )
        gold_csv = tmp_path / "gold.csv"
        gold_csv.write_text(
            "Date,Close\n"
            "2024-01-10,2000\n2024-01-11,2010\n2024-01-12,2020\n"
            "2024-01-15,2030\n2024-01-16,2025\n2024-01-17,2015\n"
            "2024-01-18,2020\n2024-01-19,2025\n2024-01-22,2030\n"
            "2024-02-10,2100\n2024-02-11,2110\n2024-02-12,2120\n"
            "2024-02-13,2130\n2024-02-14,2125\n2024-02-15,2115\n"
            "2024-02-16,2120\n2024-02-17,2125\n2024-02-20,2130\n"
            "2024-03-10,2200\n2024-03-11,2210\n2024-03-12,2220\n"
            "2024-03-13,2230\n2024-03-14,2225\n"
        )
        config = LessonBuilderConfig(
            event_data_path=data_csv,
            gold_path=gold_csv,
            output_path=tmp_path / "lessons.csv",
            horizons=(1, 5),
        )
        builder = LegacyLessonBuilder(config=config, event=ev)
        lessons = builder.build_and_save()
        assert len(lessons) > 0
        assert "event_type" in lessons.columns
        assert "pmi_trend" in lessons.columns
        assert lessons["event_type"].iloc[0] == "PMI"
