"""Tests for the GDP event implementation.

Generated by ``EventScaffolder``.
"""

from pathlib import Path
import pandas as pd
import pytest

from knowledge.events.gdp import GDPEvent
from knowledge.features.extractors.gdp import (
    GDPFeatureExtractor,
)
from knowledge.builders.lesson_builder import LessonBuilder, LessonBuilderConfig
from knowledge.lesson_summary import LessonSummaryAggregator, LessonSummaryConfig
from knowledge.events.registry import EventRegistry


class TestGDPEventFeatureExtractor:
    """Feature extraction tests."""

    def test_defines_features(self) -> None:
        ext = GDPFeatureExtractor()
        assert "previous_value" in ext.feature_definitions
        assert "gdp_change" in ext.feature_definitions
        assert "gdp_trend" in ext.feature_definitions

    def test_classifies_trend(self) -> None:
        assert GDPFeatureExtractor._classify_trend(4.0) == "gdp_expansion"
        assert GDPFeatureExtractor._classify_trend(0.5) == "gdp_contraction"
        assert GDPFeatureExtractor._classify_trend(2.0) == "gdp_stable"

    def test_extract_adds_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,3.1\n2024-02-10,2.5\n")
        ext = GDPFeatureExtractor()
        raw = pd.read_csv(csv)
        result = ext.extract(raw)
        assert "gdp_change" in result.data.columns
        assert "gdp_trend" in result.data.columns
        # After dropna, the first surviving row has the *second* CSV row's Value
        # (2.5 → gdp_stable because 1.0 <= 2.5 <= 3.0)
        assert result.data["gdp_trend"].iloc[0] == "gdp_stable"


class TestGDPEventTypeStrings:
    """Event metadata string constants."""

    def test_event_type(self) -> None:
        assert GDPEvent.event_type == "GDP"

    def test_lesson_version(self) -> None:
        assert GDPEvent.lesson_version == "gdp_gold_v1"

    def test_condition_columns(self) -> None:
        assert GDPEvent.condition_columns == ['gdp_trend']

    def test_knowledge_version(self) -> None:
        assert GDPEvent.knowledge_version == "gdp_gold_summary_v1"


class TestGDPEventMetadata:
    """StandardEventMetadata tests."""

    def test_metadata_returns_expected_values(self) -> None:
        ev = GDPEvent()
        m = ev.metadata
        assert m is not None
        assert m.country == "US"
        assert m.currency == "USD"
        assert m.unit == "annualized_percent"
        assert m.importance == 3


class TestGDPEventLoadRaw:
    """Raw data loading tests."""

    def test_returns_date_value_only(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,100\n")
        ev = GDPEvent()
        df = ev.load_raw(csv)
        assert list(df.columns) == ["Date", "Value"]

    def test_sorts_and_deduplicates(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text(
            "Date,Value\n2024-01-10,100\n2024-01-10,101\n"
            "2024-01-05,99\n"
        )
        ev = GDPEvent()
        df = ev.load_raw(csv)
        assert len(df) == 2
        assert df["Date"].iloc[0].date().isoformat() == "2024-01-05"

    def test_raises_on_missing_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "bad.csv"
        csv.write_text("Col1,Col2\n1,2\n")
        ev = GDPEvent()
        with pytest.raises(ValueError, match="missing required columns"):
            ev.load_raw(csv)


class TestGDPEventLoadAndExtract:
    """Full load + extract pipeline tests."""

    def test_includes_all_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,3.1\n2024-02-10,2.5\n")
        ev = GDPEvent()
        df = ev.load_and_extract(csv)
        assert "Date" in df.columns
        assert "gdp_change" in df.columns
        assert "gdp_trend" in df.columns

    def test_empty_on_single_row(self, tmp_path: Path) -> None:
        csv = tmp_path / "single.csv"
        csv.write_text("Date,Value\n2024-01-10,100\n")
        ev = GDPEvent()
        df = ev.load_and_extract(csv)
        assert len(df) == 0


class TestGDPEventLesson:
    """Lesson field and text tests."""

    def test_build_lesson_fields(self) -> None:
        ev = GDPEvent()
        row = pd.Series({
            "Date": pd.Timestamp("2024-01-10"),
            "Value": 3.1,
            "previous_value": 2.5,
            "gdp_change": 0.6,
            "gdp_trend": "gdp_expansion",
        })
        fields = ev.build_lesson_fields(row, "2024-01-10")
        assert "gdp_value" in fields
        assert "gdp_change" in fields
        assert "gdp_trend" in fields

    def test_lesson_text(self) -> None:
        ev = GDPEvent()
        lesson = {
            "event_date": "2024-01-10",
            "primary_horizon_days": 5,
            "gold_direction_5d": "UP",
            "gold_return_5d_pct": 1.5,
            "gdp_value": 3.1,
            "gdp_trend": "gdp_expansion",
        }
        text = ev.lesson_text(lesson)
        assert "GDP" in text
        assert "3.1" in text
        assert "gdp_expansion" in text


class TestGDPEventRegistry:
    """Registry integration tests."""

    def test_is_registered_after_import(self) -> None:
        assert EventRegistry.is_registered("GDP")

    def test_can_be_instantiated_from_registry(self) -> None:
        cls = EventRegistry.get("GDP")
        assert cls is not None
        instance = cls()
        assert instance.event_type == "GDP"


class TestGDPEventPipelineEndToEnd:
    """End-to-end: LessonBuilder -> LessonSummaryAggregator."""

    def test_knowledge_from_gdp_lessons(
        self, tmp_path: Path
    ) -> None:
        ev = GDPEvent()
        data_csv = tmp_path / "gdp.csv"
        data_csv.write_text(
            "Date,Value\n2024-01-10,3.1\n2024-02-10,2.5\n"
            "2024-03-10,1.8\n"
        )
        gold_csv = tmp_path / "gold.csv"
        gold_csv.write_text(
            "Date,Close\n"
            "2024-01-10,2000\n2024-01-11,2010\n2024-01-12,2020\n"
            "2024-01-15,2030\n2024-01-16,2025\n2024-01-17,2015\n"
            "2024-01-18,2020\n2024-01-19,2025\n2024-01-22,2030\n"
            "2024-02-10,2100\n2024-02-11,2110\n2024-02-12,2120\n"
            "2024-02-13,2130\n2024-02-14,2125\n2024-02-15,2115\n"
            "2024-02-16,2120\n2024-02-17,2125\n2024-02-20,2130\n"
            "2024-03-10,2200\n2024-03-11,2210\n2024-03-12,2220\n"
            "2024-03-13,2230\n2024-03-14,2225\n"
        )
        config = LessonBuilderConfig(
            event_data_path=data_csv,
            gold_path=gold_csv,
            output_path=tmp_path / "lessons.csv",
            horizons=(1, 5),
        )
        builder = LessonBuilder(config=config, event=ev)
        lessons = builder.build_and_save()
        assert len(lessons) > 0
        assert "event_type" in lessons.columns
        assert "gdp_trend" in lessons.columns
        assert lessons["event_type"].iloc[0] == "GDP"
