"""Tests for the FOMC event implementation.

Generated by ``EventScaffolder`` and customized for FOMC semantics.
"""

from pathlib import Path
import pandas as pd
import pytest

from knowledge.events.fomc import FOMCEvent
from knowledge.features.extractors.fomc import (
    FOMCFeatureExtractor,
)
from knowledge.builders.lesson_builder import (
    LessonBuilder,
    LessonBuilderConfig,
    LegacyLessonBuilder,
)
from knowledge.lesson_summary import LessonSummaryAggregator, LessonSummaryConfig
from knowledge.events.registry import EventRegistry


@pytest.fixture(autouse=True)
def _ensure_fomc_registered() -> None:
    if not EventRegistry.is_registered("FOMC"):
        EventRegistry.register(FOMCEvent)


class TestFOMCEventFeatureExtractor:
    """Feature extraction tests."""

    def test_defines_features(self) -> None:
        ext = FOMCFeatureExtractor()
        assert "previous_value" in ext.feature_definitions
        assert "fomc_change" in ext.feature_definitions
        assert "fomc_decision" in ext.feature_definitions

    def test_classifies_decision(self) -> None:
        assert FOMCFeatureExtractor._classify_decision(0.25) == "rate_hike"
        assert FOMCFeatureExtractor._classify_decision(-0.25) == "rate_cut"
        assert FOMCFeatureExtractor._classify_decision(0.0) == "rate_hold"

    def test_extract_adds_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n2024-02-10,5.5\n")
        ext = FOMCFeatureExtractor()
        raw = pd.read_csv(csv)
        result = ext.extract(raw)
        assert "fomc_change" in result.data.columns
        assert "fomc_decision" in result.data.columns
        assert result.data["fomc_decision"].iloc[0] == "rate_hold"

    def test_detects_hike(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.25\n2024-02-10,5.5\n")
        ext = FOMCFeatureExtractor()
        raw = pd.read_csv(csv)
        result = ext.extract(raw)
        assert result.data["fomc_decision"].iloc[0] == "rate_hike"

    def test_detects_cut(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n2024-02-10,5.25\n")
        ext = FOMCFeatureExtractor()
        raw = pd.read_csv(csv)
        result = ext.extract(raw)
        assert result.data["fomc_decision"].iloc[0] == "rate_cut"


class TestFOMCEventTypeStrings:
    """Event metadata string constants."""

    def test_event_type(self) -> None:
        assert FOMCEvent.event_type == "FOMC"

    def test_lesson_version(self) -> None:
        assert FOMCEvent.lesson_version == "fomc_gold_v1"

    def test_condition_columns(self) -> None:
        assert FOMCEvent.condition_columns == ["fomc_decision"]

    def test_knowledge_version(self) -> None:
        assert FOMCEvent.knowledge_version == "fomc_gold_summary_v1"


class TestFOMCEventMetadata:
    """StandardEventMetadata tests."""

    def test_metadata_returns_expected_values(self) -> None:
        ev = FOMCEvent()
        m = ev.metadata
        assert m is not None
        assert m.country == "US"
        assert m.currency == "USD"
        assert m.unit == "percent"
        assert m.importance == 3


class TestFOMCEventLoadRaw:
    """Raw data loading tests."""

    def test_returns_date_value_only(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n")
        ev = FOMCEvent()
        df = ev.load_raw(csv)
        assert list(df.columns) == ["Date", "Value"]

    def test_sorts_and_deduplicates(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text(
            "Date,Value\n2024-01-10,5.5\n2024-01-10,5.5\n"
            "2024-01-05,5.25\n"
        )
        ev = FOMCEvent()
        df = ev.load_raw(csv)
        assert len(df) == 2
        assert df["Date"].iloc[0].date().isoformat() == "2024-01-05"

    def test_raises_on_missing_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "bad.csv"
        csv.write_text("Col1,Col2\n1,2\n")
        ev = FOMCEvent()
        with pytest.raises(ValueError, match="missing required columns"):
            ev.load_raw(csv)


class TestFOMCEventLoadAndExtract:
    """Full load + extract pipeline tests."""

    def test_includes_all_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.25\n2024-02-10,5.5\n")
        ev = FOMCEvent()
        df = ev.load_and_extract(csv)
        assert "Date" in df.columns
        assert "fomc_change" in df.columns
        assert "fomc_decision" in df.columns

    def test_empty_on_single_row(self, tmp_path: Path) -> None:
        csv = tmp_path / "single.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n")
        ev = FOMCEvent()
        df = ev.load_and_extract(csv)
        assert len(df) == 0


class TestFOMCEventLesson:
    """Lesson field and text tests."""

    def test_build_lesson_fields(self) -> None:
        ev = FOMCEvent()
        row = pd.Series({
            "Date": pd.Timestamp("2024-01-10"),
            "Value": 5.5,
            "previous_value": 5.25,
            "fomc_change": 0.25,
            "fomc_decision": "rate_hike",
        })
        fields = ev.build_lesson_fields(row, "2024-01-10")
        assert "fomc_rate" in fields
        assert "fomc_change" in fields
        assert "fomc_decision" in fields

    def test_lesson_text_hike(self) -> None:
        ev = FOMCEvent()
        lesson = {
            "event_date": "2024-01-10",
            "primary_horizon_days": 5,
            "gold_direction_5d": "DOWN",
            "gold_return_5d_pct": -0.8,
            "fomc_rate": 5.5,
            "fomc_decision": "rate_hike",
        }
        text = ev.lesson_text(lesson)
        assert "FOMC" in text
        assert "5.5" in text
        assert "rate_hike" in text


class TestFOMCEventRegistry:
    """Registry integration tests."""

    def test_is_registered_after_import(self) -> None:
        assert EventRegistry.is_registered("FOMC")

    def test_can_be_instantiated_from_registry(self) -> None:
        cls = EventRegistry.get("FOMC")
        assert cls is not None
        instance = cls()
        assert instance.event_type == "FOMC"


class TestFOMCEventPipelineEndToEnd:
    """End-to-end: LessonBuilder -> LessonSummaryAggregator."""

    def test_knowledge_from_fomc_lessons(
        self, tmp_path: Path
    ) -> None:
        ev = FOMCEvent()
        data_csv = tmp_path / "fomc.csv"
        data_csv.write_text(
            "Date,Value\n2024-01-10,5.25\n2024-02-10,5.5\n"
            "2024-03-10,5.25\n"
        )
        gold_csv = tmp_path / "gold.csv"
        gold_csv.write_text(
            "Date,Close\n"
            "2024-01-10,2000\n2024-01-11,2010\n2024-01-12,2020\n"
            "2024-01-15,2030\n2024-01-16,2025\n2024-01-17,2015\n"
            "2024-01-18,2020\n2024-01-19,2025\n2024-01-22,2030\n"
            "2024-02-10,2100\n2024-02-11,2110\n2024-02-12,2120\n"
            "2024-02-13,2130\n2024-02-14,2125\n2024-02-15,2115\n"
            "2024-02-16,2120\n2024-02-17,2125\n2024-02-20,2130\n"
            "2024-03-10,2200\n2024-03-11,2210\n2024-03-12,2220\n"
            "2024-03-13,2230\n2024-03-14,2225\n"
        )
        config = LessonBuilderConfig(
            event_data_path=data_csv,
            gold_path=gold_csv,
            output_path=tmp_path / "lessons.csv",
            horizons=(1, 5),
        )
        builder = LegacyLessonBuilder(config=config, event=ev)
        lessons = builder.build_and_save()
        assert len(lessons) > 0
        assert "event_type" in lessons.columns
        assert "fomc_decision" in lessons.columns
        assert lessons["event_type"].iloc[0] == "FOMC"
