"""Tests for the Interest Rate event implementation.

Generated by ``EventScaffolder`` and customized for interest rate semantics.
"""

from pathlib import Path
import pandas as pd
import pytest

from knowledge.events.interest_rate import InterestRateEvent
from knowledge.features.extractors.interest_rate import (
    InterestRateFeatureExtractor,
)
from knowledge.builders.lesson_builder import LessonBuilder, LessonBuilderConfig
from knowledge.lesson_summary import LessonSummaryAggregator, LessonSummaryConfig
from knowledge.events.registry import EventRegistry


class TestInterestRateEventFeatureExtractor:
    """Feature extraction tests."""

    def test_defines_features(self) -> None:
        ext = InterestRateFeatureExtractor()
        assert "previous_value" in ext.feature_definitions
        assert "interest_rate_change" in ext.feature_definitions
        assert "interest_rate_trend" in ext.feature_definitions

    def test_classifies_trend(self) -> None:
        assert InterestRateFeatureExtractor._classify_trend(0.25) == "rate_hike"
        assert InterestRateFeatureExtractor._classify_trend(-0.25) == "rate_cut"
        assert InterestRateFeatureExtractor._classify_trend(0.0) == "rate_hold"

    def test_extract_adds_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n2024-02-10,5.75\n")
        ext = InterestRateFeatureExtractor()
        raw = pd.read_csv(csv)
        result = ext.extract(raw)
        assert "interest_rate_change" in result.data.columns
        assert "interest_rate_trend" in result.data.columns
        # After dropna, first surviving row has Value=5.75 → change=0.25 → hike
        assert result.data["interest_rate_trend"].iloc[0] == "rate_hike"


class TestInterestRateEventTypeStrings:
    """Event metadata string constants."""

    def test_event_type(self) -> None:
        assert InterestRateEvent.event_type == "INTEREST_RATE"

    def test_lesson_version(self) -> None:
        assert InterestRateEvent.lesson_version == "interest_rate_gold_v1"

    def test_condition_columns(self) -> None:
        assert InterestRateEvent.condition_columns == ['interest_rate_trend']

    def test_knowledge_version(self) -> None:
        assert InterestRateEvent.knowledge_version == "interest_rate_gold_summary_v1"


class TestInterestRateEventMetadata:
    """StandardEventMetadata tests."""

    def test_metadata_returns_expected_values(self) -> None:
        ev = InterestRateEvent()
        m = ev.metadata
        assert m is not None
        assert m.country == "US"
        assert m.currency == "USD"
        assert m.unit == "percent"
        assert m.importance == 3


class TestInterestRateEventLoadRaw:
    """Raw data loading tests."""

    def test_returns_date_value_only(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n")
        ev = InterestRateEvent()
        df = ev.load_raw(csv)
        assert list(df.columns) == ["Date", "Value"]

    def test_sorts_and_deduplicates(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text(
            "Date,Value\n2024-01-10,5.5\n2024-01-10,5.75\n"
            "2024-01-05,5.25\n"
        )
        ev = InterestRateEvent()
        df = ev.load_raw(csv)
        assert len(df) == 2
        assert df["Date"].iloc[0].date().isoformat() == "2024-01-05"

    def test_raises_on_missing_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "bad.csv"
        csv.write_text("Col1,Col2\n1,2\n")
        ev = InterestRateEvent()
        with pytest.raises(ValueError, match="missing required columns"):
            ev.load_raw(csv)


class TestInterestRateEventLoadAndExtract:
    """Full load + extract pipeline tests."""

    def test_includes_all_columns(self, tmp_path: Path) -> None:
        csv = tmp_path / "test.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n2024-02-10,5.75\n")
        ev = InterestRateEvent()
        df = ev.load_and_extract(csv)
        assert "Date" in df.columns
        assert "interest_rate_change" in df.columns
        assert "interest_rate_trend" in df.columns

    def test_empty_on_single_row(self, tmp_path: Path) -> None:
        csv = tmp_path / "single.csv"
        csv.write_text("Date,Value\n2024-01-10,5.5\n")
        ev = InterestRateEvent()
        df = ev.load_and_extract(csv)
        assert len(df) == 0


class TestInterestRateEventLesson:
    """Lesson field and text tests."""

    def test_build_lesson_fields(self) -> None:
        ev = InterestRateEvent()
        row = pd.Series({
            "Date": pd.Timestamp("2024-01-10"),
            "Value": 5.5,
            "previous_value": 5.25,
            "interest_rate_change": 0.25,
            "interest_rate_trend": "rate_hike",
        })
        fields = ev.build_lesson_fields(row, "2024-01-10")
        assert "interest_rate_value" in fields
        assert "interest_rate_change" in fields
        assert "interest_rate_trend" in fields

    def test_lesson_text(self) -> None:
        ev = InterestRateEvent()
        lesson = {
            "event_date": "2024-01-10",
            "primary_horizon_days": 5,
            "gold_direction_5d": "DOWN",
            "gold_return_5d_pct": -1.2,
            "interest_rate_value": 5.5,
            "interest_rate_trend": "rate_hike",
        }
        text = ev.lesson_text(lesson)
        assert "rate_hike" in text
        assert "5.5" in text


class TestInterestRateEventRegistry:
    """Registry integration tests."""

    def test_is_registered_after_import(self) -> None:
        assert EventRegistry.is_registered("INTEREST_RATE")

    def test_can_be_instantiated_from_registry(self) -> None:
        cls = EventRegistry.get("INTEREST_RATE")
        assert cls is not None
        instance = cls()
        assert instance.event_type == "INTEREST_RATE"


class TestInterestRateEventPipelineEndToEnd:
    """End-to-end: LessonBuilder -> LessonSummaryAggregator."""

    def test_knowledge_from_interest_rate_lessons(
        self, tmp_path: Path
    ) -> None:
        ev = InterestRateEvent()
        data_csv = tmp_path / "interest_rate.csv"
        data_csv.write_text(
            "Date,Value\n2024-01-10,5.5\n2024-02-10,5.75\n"
            "2024-03-10,5.75\n"
        )
        gold_csv = tmp_path / "gold.csv"
        gold_csv.write_text(
            "Date,Close\n"
            "2024-01-10,2000\n2024-01-11,2010\n2024-01-12,2020\n"
            "2024-01-15,2030\n2024-01-16,2025\n2024-01-17,2015\n"
            "2024-01-18,2020\n2024-01-19,2025\n2024-01-22,2030\n"
            "2024-02-10,2100\n2024-02-11,2110\n2024-02-12,2120\n"
            "2024-02-13,2130\n2024-02-14,2125\n2024-02-15,2115\n"
            "2024-02-16,2120\n2024-02-17,2125\n2024-02-20,2130\n"
            "2024-03-10,2200\n2024-03-11,2210\n2024-03-12,2220\n"
            "2024-03-13,2230\n2024-03-14,2225\n"
        )
        config = LessonBuilderConfig(
            event_data_path=data_csv,
            gold_path=gold_csv,
            output_path=tmp_path / "lessons.csv",
            horizons=(1, 5),
        )
        builder = LessonBuilder(config=config, event=ev)
        lessons = builder.build_and_save()
        assert len(lessons) > 0
        assert "event_type" in lessons.columns
        assert "interest_rate_trend" in lessons.columns
        assert lessons["event_type"].iloc[0] == "INTEREST_RATE"
