"""Quick smoke test: verify DXY enricher works with real data."""

import sys
from pathlib import Path
sys.path.insert(0, str(Path("src").resolve()))

import pandas as pd
from knowledge.context.dxy import DXYContextConfig, DXYContextEnricher

# Load real CPI lessons (already generated by pipeline)
lessons_path = Path("data/output/gate6/run1_baseline/artifacts/lessons.csv")
if not lessons_path.exists():
    print("No existing lessons found. Run gate6 validation first or use pipeline directly.")
    # Try standalone test with a minimal dataset
    lessons = pd.DataFrame({
        "event_date": ["2020-01-01", "2020-02-01", "2020-03-01", "2020-04-01", "2025-06-01"],
        "cpi_value": [100.0, 101.0, 99.0, 102.0, 110.0],
    })
else:
    lessons = pd.read_csv(lessons_path)

dxy_path = Path("data/context/dxy/dxy.csv")
config = DXYContextConfig(dxy_path=dxy_path)
enricher = DXYContextEnricher(config)
enriched = enricher.enrich(lessons)

print(f"Original lessons: {len(lessons)}")
print(f"Enriched lessons: {len(enriched)}")
print(f"New columns: {[c for c in enriched.columns if c.startswith('dxy_')]}")

# Show sample
dxy_cols = ["event_date"] + [c for c in enriched.columns if c.startswith("dxy_")]
print(enriched[dxy_cols].to_string())

# Check for NaNs
na_count = enriched["dxy_value_at_event"].isna().sum()
missing_level = (enriched["dxy_level"] == "missing_dxy_context").sum()
missing_trend = (enriched["dxy_trend"] == "missing_dxy_context").sum()
print(f"\nNaN value_at_event: {na_count}")
print(f"missing_dxy_context level: {missing_level}")
print(f"missing_dxy_context trend: {missing_trend}")
print(f"\nDXY level distribution:\n{enriched['dxy_level'].value_counts()}")
print(f"\nDXY trend distribution:\n{enriched['dxy_trend'].value_counts()}")
